### ISSUE TITLE
Add Searching algorithms for graphs

### ISSUE THREAD

**Issue by nvinayvarma189** [codeIIEST/Algorithms#104]
## DESCRIPTION

Please provide a short, clear description of the problem
need to add searching algorithms for graphs
## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem
--
## EXPECTED OUTCOME
--
What did you expect to happen
--
## ACTUAL OUTCOME
--
What actually happened
--
### Proposed Solution [optional]

If you know how to solve the above, please provide details here.
I want to add the algorithms for graphs in java

**Comment by nvinayvarma189** [comment]
can the kwoc tag added to this issue? @prateekiiest

**Comment by abhisheknalla** [comment]
Can I take this issue up?. I can code in C and C++ well.

**Comment by prateekiiest** [comment]
@nvinayvarma189 Some test cases are still failing in your PR. 
@abhisheknalla , I appreciate your contribution, but if the other PR is not good enough meaning if tests are failing for prolonged time, then you may work on this.

Until then you can look for the issues related to the Projects

**Comment by prateekiiest** [comment]
@nvinayvarma189  make sure to add a readme file for the BFS
