### ISSUE TITLE
Cycle detection algorithm

### ISSUE THREAD

**Issue by nvinayvarma189** [codeIIEST/Algorithms#109]
## DESCRIPTION

I want to add Cycle detection algorithm for a Undirected graph

## STEPS TO REPRODUCE

--
## EXPECTED OUTCOME

--

## ACTUAL OUTCOME

--

### Proposed Solution [optional]

upload the cycle detection algorithm for undirected graph

**Comment by abhisheknalla** [comment]
Can I take this issue up?
