### ISSUE TITLE
program for stack

### ISSUE THREAD

**Issue by shiveshchoudhary** [codeIIEST/Algorithms#111]
## DESCRIPTION
adding stack program in cpp . stack is abstract data type with two principle operations push and pop.

## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem

## EXPECTED OUTCOME
push,pop,peek operations will tested with an array and push will add elements ,pop will destroy the topmost element peek will be used to view topmost element

## ACTUAL OUTCOME
same as expected.

### Proposed Solution [optional]

upload the code for the operations.
i am assigning it to myself and adding the program in cpp

**Comment by prateekiiest** [comment]
@shiveshchoudhary go ahead please

**Comment by prateekiiest** [comment]
already there was one issue
