### ISSUE TITLE
Math Algorithms -> Eucilds Algorthim application (GCD,LCM) and Prime related Algos

### ISSUE THREAD

**Issue by Nihalh55** [codeIIEST/Algorithms#116]
## DESCRIPTION OF ALGORITHMS TO BE CODED

To solve the following problems:
1) GCD and LCM of numbers
2) Extended Euclid Algo application to find GCD
3) Steins Algorithm
4) Polland Rho's Prime Factorisation Algo
5) Finding divisiors of a number
6) Sieve of Erathostheneses

**Comment by prateekiiest** [comment]
That's good @Nihalh55 
Please go ahead
