### ISSUE TITLE
Maths Algorithms

### ISSUE THREAD

**Issue by abhisheknalla** [codeIIEST/Algorithms#118]
Can I work on coding the Algorithms to solve the following problems
1. Fast Fourier Transformation
2. Sum of squares of first N natural numbers
3. Checking for integer overflow on multiplication
4. Convert Degree to Radian
5. K-th Primes.

**Comment by prateekiiest** [comment]
sure @abhisheknalla :)

**Comment by prateekiiest** [comment]
I guess you already sent a PR for this.

I am closing this. 😄 . Open if any updates
