### ISSUE TITLE
Binary search in Python

### ISSUE THREAD

**Issue by minchi19** [codeIIEST/Algorithms#124]
I want to add binary search algo in python language
will add Readme.md file also.

**Comment by prateekiiest** [comment]
Thanks for the idea @minchi19 .
But I feel working on the same code in some different language especially in Binary search will not add much value to the repo.

We encourage adding Python languages for codes having more mathematical analysis or statistics.
Other wise the given code is good to go.

You can try out with maths problems if you want :)
