### ISSUE TITLE
Heap Sort Readme looks not good

### ISSUE THREAD

**Issue by prateekiiest** [codeIIEST/Algorithms#127]
Remove the extra ## heading formats in the readme under HeapSort folder.

since @AdvikEshan you worked on this, I am assigning to you

![screenshot 2017-12-08 13 22 39](https://user-images.githubusercontent.com/16035442/33756341-0c949bc4-dc1b-11e7-9ba2-5cea198791f3.png)

**Comment by nitishtw** [comment]
Ohk sir  I'll do it by today evening !!

**Comment by nipunjain099** [comment]
May I do this sir.
