### ISSUE TITLE
Math based algorithms

### ISSUE THREAD

**Issue by rahulkumaran** [codeIIEST/Algorithms#128]
## DESCRIPTION
WIll we implementing a few math based algorithms like:
(1) Factorial 
(2) Fibonacci Series
(3) Project Euler problem-1
(4) An algorithm for a Random Number Generator

## STEPS TO REPRODUCE

Will be coding the following algorithms in C,C++ or Python.

### Proposed Solution [optional]
I'd like this issue to be assigned to me so that I can implement the following.

**Comment by rahulkumaran** [comment]
@prateekiiest can you assign this to me? :)

**Comment by prateekiiest** [comment]
This are really novice problems
It could be better if you can work after problem 20

**Comment by rahulkumaran** [comment]
Okie I'll have a look at it and get back to you!
