### ISSUE TITLE
Greedy -> Activity Selection Problem

### ISSUE THREAD

**Issue by MuskanSapolia** [codeIIEST/Algorithms#130]
## DESCRIPTION

Given n activities with their start and finish times, Select the maximum number of activities that can be performed by a single person, assuming that a person can only work on a single activity at a time.

**Comment by prateekiiest** [comment]
please add under greedy section with proper readme and file name

**Comment by MuskanSapolia** [comment]
i added the code to this problem few days back but it seems that u've not merged the pull request. Is the expected solution different or any other issue? I am contributing for the first time so please do tell me if there is any problem.

**Comment by prateekiiest** [comment]
@MuskanSapolia 👋  , there was a problem with git untrack files from my side.
So all the PRs that were opened got closed automatically.

I would request you to send a PR again for this.
Regrets for what had happened :face_with_head_bandage:
