### ISSUE TITLE
Missing: Linked List operations based on Arrays

### ISSUE THREAD

**Issue by Zanark** [codeIIEST/Algorithms#133]
## DESCRIPTION

There is a file containing all the operations that can be performed on a linked list in **Algorithms/Competitive Coding/Linked List**  but it's only pointer based. 

I would like to add an array based 'Linked_list_operation' file using **C++** and if allowed I would like to rename the current one to 'Linked_list_operation_based_on_pointers'

## STEPS TO REPRODUCE

1. Adding the new file containing Linked List operations based on array
2. Renaming the current file to 'Linked_list_operation_based_on_pointers'

## EXPECTED OUTCOME

The repository will now have both array based and pointer based Linked List operations files. 

## ACTUAL OUTCOME

--
### Proposed Solution

I would like to add an array based 'Linked_list_operation' file using **C++** and if allowed I would like to rename the current one to 'Linked_list_operation_based_on_pointers'

**Comment by prateekiiest** [comment]
create two folders then.
The already present one under `Pointer based LLs` and the other one under `Array Implementation`

**Comment by Zanark** [comment]
Thank You Sir, I'll submit a PR soon
