### ISSUE TITLE
LINKED LISTS, SEARCHING, SORTING AND OTHER ALGORITHMS

### ISSUE THREAD

**Issue by suhitmajumdar** [codeIIEST/Algorithms#144]
## DESCRIPTION

I want to propose new commits which include files containing a number of important algorithms in  C or C++ .

## STEPS TO REPRODUCE

New commits can be added with the required algorithms.

## EXPECTED OUTCOME

A rich  repository with a number of useful algorithms for student purpose like linked lists, stacks,queues,circular queues ,searching and sorting techniques etc.

What did you expect to happen

## ACTUAL OUTCOME

The proposed outcome

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by prateekiiest** [comment]
Most of them are already implemented in this repo
