### ISSUE TITLE
Contributiing Guidelines leads to 404 error

### ISSUE THREAD

**Issue by AdilMah** [codeIIEST/Algorithms#160]
## DESCRIPTION

Please provide a short, clear description of the problem

## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem

## EXPECTED OUTCOME

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by prateekiiest** [comment]
please resolve it

**Comment by AdilMah** [comment]
The structure of my forked repo and this repo has changed..

**Comment by prateekiiest** [comment]
Its fixed.
I am closing this
