### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by ManognaMutyala** [codeIIEST/Algorithms#169]
## DESCRIPTION

I would like to document prims ,kruskal,Dijkstra's algorithms

## STEPS TO REPRODUCE

Will be coding in Java,C and describing pseudocode for algo

**Comment by prateekiiest** [comment]
Already there in the github repo, I guess

**Comment by ManognaMutyala** [comment]
It is in cpp but not in java.So could I work on it  @prateekiiest ?

**Comment by prateekiiest** [comment]
I know that @ManognaMutyala , but I guess that will not add much value in the code base.
Because C++ is basic, a novice can understand that. So adding an extra language is redundant in this case.

😅
