### ISSUE TITLE
Dynamic programming

### ISSUE THREAD

**Issue by ManognaMutyala** [codeIIEST/Algorithms#191]
I would like to document 0-1 Knapsack problem using dynamic programming techniques along with time and space complexity.This repository contains knapsack using greedy programming technique but not dynamic programming.Could I work on this issue?

**Comment by prateekiiest** [comment]
ok, sure 👍

**Comment by prateekiiest** [comment]
Assigned you. Welcome to the team ! 😃

**Comment by prateekiiest** [comment]
I am closing this. 😄 . Open if any updates
