### ISSUE TITLE
DFS and BFS

### ISSUE THREAD

**Issue by Ankitr19** [codeIIEST/Algorithms#205]
## DESCRIPTION

Depth first search and Breadth first serach in grpah

## STEPS TO REPRODUCE

--

## EXPECTED OUTCOME

--

## ACTUAL OUTCOME

--

### Proposed Solution [optional]

--

**Comment by prateekiiest** [comment]
One issue was already for DP problem.

You can check there.

I am closing this. 😄 . Open if any updates
