### ISSUE TITLE
Please review PR #248

### ISSUE THREAD

**Issue by abhisheknalla** [codeIIEST/Algorithms#252]
## DESCRIPTION

Please provide a short, clear description of the problem

## STEPS TO REPRODUCE

Please list the steps to reproduce the above problem

## EXPECTED OUTCOME

What did you expect to happen

## ACTUAL OUTCOME

What actually happened

### Proposed Solution [optional]

If you know how to solve the above, please provide details here.

**Comment by baolao** [comment]
Please help
