### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by ashubly25** [codeIIEST/Algorithms#254]
## DESCRIPTION
I would like to make this repository more friendly to the beginners. Thus I wanted to improve the documentation.

## STEPS TO REPRODUCE
I would make it more informative about the programs that are available in the folders.

## EXPECTED OUTCOME
More people will able to engage in this repository. As people will be guided with proper documentation

## ACTUAL OUTCOME
I would be able to replicate the expected out come

### Proposed Solution [optional]
Make it more informative to people in every stage be it newbie intermediate or expert. Proper documentation is always needed for a better repository

**Comment by prateekiiest** [comment]
sure we would be happy to get that going.

**Comment by ashubly25** [comment]
thanks a lot.
