### ISSUE TITLE
Classify algorithms

### ISSUE THREAD

**Issue by dhruvapte26** [codeIIEST/Algorithms#28]
Instead of searching all the through the list, how about creating folders like `Bit manipulation`, `dynamic programming` , `greedy algorithms` and so on. This would create a neat  and tidy repo

**Comment by prateekiiest** [comment]
Yeah, thats a good design. But most of the code written here are in a modular fashion, I guess with separate folders.

If we implement some of the common greedy problems, or bit manipulation ones, then it is better to go with the modular way as you said

**Comment by dhruvapte26** [comment]
Yes, as we proceed with more algorithms, we can classify them :smile:

**Comment by prateekiiest** [comment]
I am closing this as of now
