### ISSUE TITLE
Write a contributing.md

### ISSUE THREAD

**Issue by dhruvapte26** [codeIIEST/Algorithms#74]
There is no format for PRs and how to contribute. There should be a `contributing.md`

**Comment by prateekiiest** [comment]
yeah, can you please add one?

you can see in the insights -> collaborators

**Comment by dhruvapte26** [comment]
@prateekiiest , you have mistaken my point completely. I meant on a file on "how to contribute" not a "list of contributors" :smile:

**Comment by prateekiiest** [comment]
I know that @the-ethan-hunt , click on community , not collaborators. You will find the details there

**Comment by dhruvapte26** [comment]
Apart from the basic outline, do we need something else?
Basic outline:
- Only one algo per PR
- Algo to be in C/C++/Python/Java
- A small `readme.md` included with the algo to describe it in short. Anything else?

**Comment by prateekiiest** [comment]
yeah, that's better. 
First make the basic one. As time goes more modification can be made.
