### ISSUE TITLE
Uploading code along with some video resources on different topics

### ISSUE THREAD

**Issue by prateekiiest** [codeIIEST/Algorithms#8]
I wanna upload some resources here, for everyone to know the basics. I came across these resources in another repo and I feel it will help everyone more.
I will be uploading the codes for these alongside as well

**Comment by smitbose** [comment]
yeah sure

**Comment by prateekiiest** [comment]
ok i will be sending a PR regarding this shortly

**Comment by smitbose** [comment]
If you are going to upload videos that you have downloaded from some site, then you can add the links, as adding videos itself, unless there is no other way, will make the size big, for someone cloning it

**Comment by prateekiiest** [comment]
OK, i will  be posting links then
