### ISSUE TITLE
Have a separate folder for sorting algorithms written in Python

### ISSUE THREAD

**Issue by rahulkumaran** [codeIIEST/Algorithms#80]
I think it would be better if we create a separate folder for sorting algorithms in python as there might be people who only know Python and might know C or C++
As a result it might become difficult for them to comprehend the sorting algos in C and C++
Therefore I'd like to assign this task of creating a separate folder with Sorting algos in Python and write a couple of sorting algos into it too!

**Comment by rahulkumaran** [comment]
@prateekiiest Please do have a look at this :)

**Comment by prateekiiest** [comment]
It is quite redundant to have the same code written in a different language over and over with no space for new algorithms. 

We can go for this provided we have a good number of such cases.

I am closing this now
