### ISSUE TITLE
ANNOUNCEMENT !!  Code Base File Structure needs changing

### ISSUE THREAD

**Issue by prateekiiest** [codeIIEST/Algorithms#82]
So the current code base contains all the algorithms and ds codes in a hapazard way
We intend to have a more organised structure

So the major directories will include some thing like this

- Security Algorithms
- Competitve Programming Algo+Ds
- Machine Learning Algos
- Statistical / Mathematical Algos

Please do not submit any new PR to the master now. Once the file gets structured, you are free to submit.

**Comment by florist-notes** [comment]
Ok, Machine Learning will come too.Great.

**Comment by prateekiiest** [comment]
see issue #85
