### ISSUE TITLE
ANNOUNCEMENT !!! UPDATE YOUR FORK

### ISSUE THREAD

**Issue by prateekiiest** [codeIIEST/Algorithms#85]
### The following PR is updating the file structure in your forks.

For those comfortable with GitHub , it should not be much of a problem.

----------------------------------------------------

## Make sure to merge them

**Comment by florist-notes** [comment]
needed file structure update.

**Comment by florist-notes** [comment]
@prateekiiest  I merged my repo & its updated now.
