### ISSUE TITLE
Readme transfer for sort and search

### ISSUE THREAD

**Issue by prateekiiest** [codeIIEST/Algorithms#92]
The current readme contains only search and sort algo description.

Transfer into  corresponding directories.

Like `Competitive_Programming/Sorting/Sorting_Readme.md`

`Competitive_Programming/Searching/Searching_Readme.md`

**Comment by rahulkumaran** [comment]
So it's like you want a separate README In the Sorting directory and a separate one in the Searching directory?

**Comment by prateekiiest** [comment]
yes @rahulkumaran

**Comment by rahulkumaran** [comment]
I'd like to take this issue up, if it's fine with you
